### ISSUE TITLE
Issues with localised shop's domain

### ISSUE THREAD

**Issue by Chrisi1321** [ZiZuu-store/PrestaShop_module-zzSEOtk#1] opened 2015-05-19 14:54 UTC
Hi!
First of all, thanks for your work, I really appreciate it.
I uses your module on PS. 1.6.0.13, but unfortunately it produces wrong urls.

![1](https://cloud.githubusercontent.com/assets/11335735/7706024/329b466e-fe48-11e4-9bd5-3cbd786674bb.png)

but it should be like this :

![2](https://cloud.githubusercontent.com/assets/11335735/7706031/3a2d39be-fe48-11e4-9ee0-9599979c848d.png)

Could you be so kind and check that again?

**Comment by ZiZuu-store** [comment] 2015-05-21 07:19
Hi @Chrisi1321,
  thank you for your report. Unfortunately it is a known issue and it seems due to some internal PS bug .. the Link method that **should** give us the right URL does not works as it should.

We already provided two Patch Requests (the first one already being merged), but they should not suffice.

We are investigating the root cause, but not luck for now.

**Comment by ZiZuu-store** [comment] 2015-05-21 08:04
Please give a try to actual dev .. a dirty fix .. hope could work even if not beautiful

**Comment by ZiZuu-store** [comment] 2015-05-21 08:04
The PrestaShop forum thread on this issue is here https://www.prestashop.com/forums/topic/328680-hreflang-and-canonical-links-creation-on-prestashop-16/

**Comment by ZiZuu-store** [comment] 2015-05-21 09:01
We already pull two requests to try to fix the strange Link::getPageLink() behaviour  https://github.com/PrestaShop/PrestaShop/pull/2958
https://github.com/PrestaShop/PrestaShop/pull/2888

As far as we know they do not suffice .. it would be nice to reference this problem in PS tracker ..

**Comment by Chrisi1321** [comment] 2015-05-22 13:47
Hi!

First of all could be please be so kind and rename the module to only lowercases?
Otherwise you can't install it.

Further the fix is not working for me, it still produces the wrong countrycodes.

When I turn dev mode on i get this errors:

Notice: Undefined index: current_domain in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

Notice: Trying to get property of non-object in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

Notice: Undefined index: current_domain in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

Notice: Trying to get property of non-object in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

Notice: Undefined index: current_domain in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

Notice: Trying to get property of non-object in /home/.sites/722/site4724782/web/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 51

**Comment by ZiZuu-store** [comment] 2015-05-22 14:12
Well,

The module name is already lowercase, it's only the github repo to be not .. as you are testing a developing code you have to manually rename the folder in the zip (or wherever your deploy method require). When I release a new version I upload the zip with the folder already renamed 

$current_domain was my error, sorry

try actual code plz

Thank you

**Comment by Chrisi1321** [comment] 2015-05-22 14:22
Perfect! 
It works now, thanks again for you work

**Comment by ZiZuu-store** [comment] 2015-05-22 18:51
:) very nice

You are welcome, thanks for testing

Have a nice WE

Il venerdì 22 maggio 2015, Chrisi1321 <notifications@github.com> ha scritto:

> Perfect!
> It works now, thanks again for you work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/PrestaShop_module-zzSEOtk/issues/1#issuecomment-104672827>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment] 2015-07-17 17:41
@Chrisi1321 can you try the actual dev version? 
Have rewritten everything by scratch .. even canonical url should work fine now

If you can confirm I'll deploy a stable release

Thank you

**Comment by Chrisi1321** [comment] 2015-07-19 14:50
Hi!
Great work, everything seems to work even canonical urls.
Thanks

**Comment by Chrisi1321** [comment] 2015-07-20 18:46
Hi!

Oh I just found out that the hreflang are always the same on the homepage, on other sites it works perfect.

Take a look at aktiv-naturheilmittel.at

Thanks

**Comment by ZiZuu-store** [comment] 2015-07-20 22:12
@Chrisi1321 should be ok now ..

**Comment by ZiZuu-store** [comment] 2015-07-21 15:03
Ok I released the first stable version.

https://github.com/ZiZuu-store/PrestaShop_module-zzSEOtk/releases/tag/v1.0.0

Thank you for your feedback and help :)

**Closed by ZiZuu-store** 2015-07-21 15:03 UTC
Labels: bug, _better_solution, _workaround

**Comment by Chrisi1321** [comment] 2015-07-24 14:52
Hi!

Could you take a look at the canonical url again?
I don't know why, but some URLs are wrong.

For instance points : 

www.aktiv-naturheilmittel.de/blog

to

www.aktiv-naturheilmittel.de/index.php?controller=list

**Comment by ZiZuu-store** [comment] 2015-07-24 15:03
Please open another issue for canonical :)
